### ISSUE TITLE
Implement `sources` table in the config parser

### ISSUE THREAD

**Issue by wizard-28** [pacstall/libpacstall#19]
Here's the last agreed upon template of the table:
```toml
[sources.official]
url = "https://github.com/pacstall/pacstall-programs"
aliases = ["main", "etc"]
preference = 1

[sources.custom1]
url = "customUrl1"
aliases = ["hydra", "custom alias 2"]
preference = 2
```

Here's how the raw parsed dictionary looks like:

```python
{
│   'sources': {
│   │   'official': {'url': 'https://github.com/pacstall/pacstall-programs', 'aliases': ['main', 'etc'], 'preference': 1},
│   │   'custom1': {'url': 'customUrl1', 'aliases': ['hydra', 'custom alias 2'], 'preference': 2}
│   }
}
```

**Comment by wizard-28** [comment]
```toml
[settings]
jobs = 10
editor = "emacs"

[[repositories]]
name = "official"
url = "https://github.com/pacstall/pacstall-programs"
preference = 1

[[repositories]]
name = "third_party"
url = "https://github.com/user/third-party"
preference = 2
```

This is the format we settled on.
